title: "test automation"
header-img: img/bg-index.jpg
email: "your-email@example.com"
copyright_name: "lucy suslova"
description: "short notes"
name: "test automation notes"
baseurl: ""
url: "https://lucysuslova.github.io"

# Social Profiles
twitter_username:  luciesuva
github_username:   lucysuslova
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
highlighter:       rouge
permalink:         pretty
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-cayman
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]