title:             Test Automation
email:             your-email@example.com
description:       Quick Automation Notes
author:            Lucy
baseurl:           "/home"
url:               "http://lucysuslova.github.io"

# Social Profiles
twitter_username:  luciesuva
github_username:   lucysuslova
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-cayman