# Site settings
title: "test automation"
header-img: img/bg-index.jpg
email: lucysuslova@gmail.com
copyright_name: Lucy Suslova
description: "short notes"
name: "test automation short notes"
baseurl: ""
url: "https://lucysuslova.github.io"
twitter_username: luciesuva
github_username:  lucysuslova
email_username:  lucysuslova@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
#google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]
